version: "3.8"
services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    volumes:
      - ../client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["yarn", "dev", "--host"]
    depends_on:
      - server
    networks:
      - blog-network

  server:
    build:
      context: ../functions
      dockerfile: Dockerfile
    volumes:
      - ../functions:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: ["yarn", "start"]
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
